ROOT_DIR := $(realpath $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/..)
langs = cs
top_layer = a
name = legaltext
source_urls = https://lindat.mff.cuni.cz/*/*/*/*/*/*/cltt_1.0.zip
vertical_subdir = $(vertical_dir)/monolingual/legaltext/

include $(ROOT_DIR)/../../../scripts/common.mk


#clean:
#	rm -f "$(output_paths)"

#$(output_paths): $(input_paths)
#	cat $+ > $@
