ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/../
langs = en
top_layer = m
name = aclrd20
source_urls = https://lindat.mff.cuni.cz/*/*/*/*/*/*/distribution.zip
vertical_subdir = $(vertical_dir)/monolingual/aclrd/2.0

include $(ROOT_DIR)/../../../scripts/common.mk
