ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/../
lang_a = en
column_a = 1
lang_b = he
column_b = 2
langs = $(lang_a) $(lang_b)
top_layer = a
name = Haaretz_1.0
source_urls = fake_corpus.gz 
vertical_subdir = $(vertical_dir)/parallel/Haaretz/1.0

include $(ROOT_DIR)/../../../scripts/common.mk
