ROOT_DIR := $(realpath $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/..)
lang_a = cs
column_a = 1
lang_b = la
column_b = 2
langs = $(lang_a) $(lang_b)
top_layer = m
name = Summa
source_urls = https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11858/00-097C-0000-0001-4909-7/corpus_both
vertical_subdir = $(vertical_dir)/parallel/Summa

include $(ROOT_DIR)/../../../scripts/common.mk
