ROOT_DIR := $(realpath $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/..)
lang_a = en
column_a = 1
lang_b = ta
column_b = 2
langs = $(lang_a) $(lang_b)
top_layer = w
name = EnTam
source_urls = https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-1454/en-ta-parallel-v2.tar.gz
vertical_subdir = $(vertical_dir)/parallel/EnTam

include $(ROOT_DIR)/../../../scripts/common.mk
