ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/../
langs = cs
top_layer = a
name = testsyntax
source_urls = https://lindat.mff.cuni.cz/*/*/*/*/*/*/output_5792
vertical_subdir = $(vertical_dir)/monolingual/test_syntax/

include $(ROOT_DIR)/../../../scripts/common.mk


#clean:
#	rm -f "$(output_paths)"

#$(output_paths): $(input_paths)
#	cat $+ > $@
