ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))/../
template_dir=../templates
links_filename=sample_list
vertical_dir=/opt/projects/lindat-services-kontext/devel/data/corpora/vert/monolingual/W2C
registry_dir=/opt/projects/lindat-services-kontext/devel/data/corpora/registry
input_dir=../input
output_dir=../output
links=`cat $(links_filename)`

template:
	@while read -r file; do \
		echo "$$file"; \
	done <$(links_filename) 



#$(foreach lang,$(langs),$(eval $(call make_output,$(lang))))

































